require("prototypes.final-fixes.trigger-tech")
require("prototypes.final-fixes.asteroids")
require("prototypes.final-fixes.biter-nests")
require("prototypes.final-fixes.enforce-rifle-ammo")
require("prototypes.final-fixes.enforce-k2-items")
require("prototypes.final-fixes.banish-basic-card")
require("prototypes.final-fixes.labs-fixes")
require("prototypes.final-fixes.surface-conditions")
require("prototypes.final-fixes.recycling")

require("prototypes.compatibility.aai-industry")
require("prototypes.compatibility.planets.muluna-final")

local api = require("__Krastorio2__.prototypes.libraries.space-age-warning")
api.disable_space_age_warning()
